- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/leo_marsyard/model/arm/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/world/leo_marsyard/pose/info"
  gz_topic_name: "/world/leo_marsyard/pose/info"
  ros_type_name: "geometry_msgs/msg/PoseArray"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/model/arm/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS







# (Recommended) Odometry from DiffDrive â†’ ROS
- ros_topic_name: "/odom"
  gz_topic_name: "/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS







# IMU data
- ros_topic_name: "/imu"
  gz_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS



- ros_topic_name: "/world/leo_marsyard/light_config"
  gz_topic_name: "/world/leo_marsyard/light_config"
  ros_type_name: "ros_gz_interfaces/msg/Light"
  gz_type_name: "gz.msgs.Light"
  direction: GZ_TO_ROS



- ros_topic_name: "/arm/arm_shoulder_joint/cmd_pos"
  gz_topic_name:  "/model/arm/joint/arm_shoulder_joint/cmd_pos"
  ros_type_name:  "std_msgs/msg/Float64"
  gz_type_name:   "gz.msgs.Double"
  direction:      ROS_TO_GZ

- ros_topic_name: "/arm/arm_elbow_joint/cmd_pos"
  gz_topic_name:  "/model/arm/joint/arm_elbow_joint/cmd_pos"
  ros_type_name:  "std_msgs/msg/Float64"
  gz_type_name:   "gz.msgs.Double"
  direction:      ROS_TO_GZ

- ros_topic_name: "/arm/arm_gripper_base_joint/cmd_pos"
  gz_topic_name:  "/model/arm/joint/arm_gripper_base_joint/cmd_pos"
  ros_type_name:  "std_msgs/msg/Float64"
  gz_type_name:   "gz.msgs.Double"
  direction:      ROS_TO_GZ

- ros_topic_name: "/arm/arm_base_joint/cmd_pos"
  gz_topic_name:  "/model/arm/joint/arm_base_joint/cmd_pos"
  ros_type_name:  "std_msgs/msg/Float64"
  gz_type_name:   "gz.msgs.Double"
  direction:      ROS_TO_GZ

- ros_topic_name: "/arm/arm_wrist_joint/cmd_pos"
  gz_topic_name:  "/model/arm/joint/arm_wrist_joint/cmd_pos"
  ros_type_name:  "std_msgs/msg/Float64"
  gz_type_name:   "gz.msgs.Double"
  direction:      ROS_TO_GZ

- ros_topic_name: "/arm/arm_gripper_left_joint/cmd_pos"
  gz_topic_name:  "/model/arm/joint/arm_gripper_left_joint/cmd_pos"
  ros_type_name:  "std_msgs/msg/Float64"
  gz_type_name:   "gz.msgs.Double"
  direction:      ROS_TO_GZ

- ros_topic_name: "/arm/arm_gripper_right_joint/cmd_pos"
  gz_topic_name:  "/model/arm/joint/arm_gripper_right_joint/cmd_pos"
  ros_type_name:  "std_msgs/msg/Float64"
  gz_type_name:   "gz.msgs.Double"
  direction:      ROS_TO_GZ



