# Default initial positions for arm's ros2_control fake system

initial_positions:
  arm_base_joint: 0
  arm_elbow_joint: 1.240
  arm_gripper_base_joint: 0
  arm_gripper_left_joint: 0
  arm_shoulder_joint: 0.700
  arm_wrist_joint: 1.190