# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - arm_base_joint
      - arm_shoulder_joint
      - arm_elbow_joint
      - arm_wrist_joint
    action_ns: follow_joint_trajectory
    default: true
    
  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - arm_gripper_base_joint
      - arm_gripper_left_joint
    action_ns: follow_joint_trajectory
    default: true 